projects:
  twitterclone:
    schemaPath: src/graphql/schema.json
    includes:
      - graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
